# Exercise: Create your own database using a compressed binary file

## Generate Fake Data File

In [293]:
!pip install Faker

Requirement already satisfied: Faker in /usr/local/lib/python3.10/dist-packages (19.12.0)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker) (1.16.0)

In [294]:
from faker import Faker
import random
import pandas as pd
import os
import numpy as np

#create 1000.0000 users file

user_columns = ['id','name','email','phone','company','street','street_number', 'zipcode','country','birthdate','deleted']

#User storage: name:
#id, street_number: 8 bytes (2 x 32 bitnumbers between 0 and 2^31)
#name','email','phone','company','street','zipcode','country: strings of n characters requires n bytes: e.g. +-100 bytes
def generate_data(size):
  users = []
  fake = Faker()
  for i in range(0,size):
    user = [i, fake.name(), fake.ascii_email(), fake.basic_phone_number(), fake.company(), fake.street_name(), random.randint(1,1000), fake.zipcode(), fake.country(), f'{random.randint(1970,2005)}-{random.randint(1,12)}-{random.randint(1,28)}', 0]
    users.append(user)
  df = pd.DataFrame(users,columns=user_columns)
  return df

size = 10000
df = generate_data(size) #Takes about 1 minutes to run or about 12 minutes for 1000000 rows
display(df)

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,06490,Nigeria,1995-2-5,0
2,2,Danielle Sellers,katiecarroll@mcbride.com,267-932-7977,Macdonald Group,Spears Course,854,18101,Cayman Islands,1995-3-24,0
3,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,Papua New Guinea,2003-9-24,0
4,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,Iran,1970-6-23,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Angela Vance,ryan17@yahoo.com,993-213-6082,Mendoza Group,Caleb Lakes,212,38438,Martinique,1975-12-24,0
9996,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,03962,Samoa,1984-5-14,0
9997,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,Norway,1988-10-17,0
9998,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,Oman,1985-8-19,0
9999,9999,Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0

## Save and load CSV file

In [295]:
import time

start = time.time()
fname = 'fake_users.csv'
df.to_csv(fname, index=False)
file_size = os.stat(fname).st_size
print(f"CSV file size is {file_size}B. Elapsed: {time.time()-start}s")
#File Size in Bytes is 1182617 (or on average 120 bytes per record) in csv.

CSV file size is 1202309B. Elapsed: 0.0760650634765625s

In [296]:
start = time.time()
df = pd.read_csv('fake_users.csv')
print(f"Loading CSV. Elapsed: {time.time()-start}s")
display(df)
display(df.describe(include='all'))

Loading CSV. Elapsed: 0.044766902923583984s

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,6490,Nigeria,1995-2-5,0
2,2,Danielle Sellers,katiecarroll@mcbride.com,267-932-7977,Macdonald Group,Spears Course,854,18101,Cayman Islands,1995-3-24,0
3,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,Papua New Guinea,2003-9-24,0
4,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,Iran,1970-6-23,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Angela Vance,ryan17@yahoo.com,993-213-6082,Mendoza Group,Caleb Lakes,212,38438,Martinique,1975-12-24,0
9996,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,3962,Samoa,1984-5-14,0
9997,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,Norway,1988-10-17,0
9998,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,Oman,1985-8-19,0
9999,9999,Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
count,10000.00000,10000,10000,10000,10000,10000,10000.0000,10000.000000,10000,10000,10000.0
unique,NaN,9369,9947,10000,8657,9431,NaN,NaN,243,6808,NaN
top,NaN,James Williams,gpoole@gmail.com,698-736-9201,Miller Inc,Smith Plains,NaN,NaN,Congo,1998-6-19,NaN
freq,NaN,7,2,1,16,4,NaN,NaN,89,8,NaN
mean,4999.50000,NaN,NaN,NaN,NaN,NaN,501.2768,50042.469300,NaN,NaN,0.0
std,2886.89568,NaN,NaN,NaN,NaN,NaN,286.0996,28708.945696,NaN,NaN,0.0
min,0.00000,NaN,NaN,NaN,NaN,NaN,1.0000,521.000000,NaN,NaN,0.0
25%,2499.75000,NaN,NaN,NaN,NaN,NaN,255.0000,24785.750000,NaN,NaN,0.0
50%,4999.50000,NaN,NaN,NaN,NaN,NaN,504.5000,50111.500000,NaN,NaN,0.0
75%,7499.25000,NaN,NaN,NaN,NaN,NaN,748.0000,75016.250000,NaN,NaN,0.0
max,9999.00000,NaN,NaN,NaN,NaN,NaN,1000.0000,99950.000000,NaN,NaN,0.0

In [297]:
#get some stats required for encoding, such as length of faker strings
for col in df.columns:
  if pd.api.types.is_int64_dtype(df[col].iloc[0]):
    print(f'col {col} is integer. range: {df[col].min()}-{df[col].max()}. unique: {df[col].nunique()}')
  elif isinstance(df[col].iloc[0],str):
    print(f'col {col} is string. range: {df[col].apply(len).min()}-{df[col].apply(len).max()}. unique: {df[col].nunique()}')

col id is integer. range: 0-9999. unique: 10000
col name is string. range: 7-27. unique: 9369
col email is string. range: 13-44. unique: 9947
col phone is string. range: 10-13. unique: 10000
col company is string. range: 6-35. unique: 8657
col street is string. range: 6-22. unique: 9431
col street_number is integer. range: 1-1000. unique: 1000
col zipcode is integer. range: 521-99950. unique: 9529
col country is string. range: 4-51. unique: 243
col birthdate is string. range: 8-10. unique: 6808
col deleted is integer. range: 0-0. unique: 1

## Encode and decode tuple to fixed-lengh binary string

In [298]:
#convert tuple to binary
import struct #See https://docs.python.org/3/library/struct.html

"""
Using struct python package to convert to binary vector
">" : litle endian (general format that defined order)
"H" " unsigned short integer (2 bytes )
"I" :  unsigned integer (4 bytes)
"32s" = string of max length 32 (32 bytes). If string is smaller, padding with 0 (less efficient)
columns: ['id','name','email','phone','company','street','street_number', 'zipcode','country','birthdate']
            I    32s    64s      16s     64s      32s          H             I          64s      16s
"""
format = '>I32s64s16s64s32sHI64s16sI'
size_user = struct.calcsize(format)
print(f'size of user: {size_user}B')

def encode_user(user_row):
  """
  Convert user tuple to fixed-length binary vector
  :param user_row: user tuple/array where colums are ['id','name','email','phone',...]
  :return: binary representation of user tuple
  """
  values = [ value.encode('ascii') if isinstance(value,str) else value for value in user_row]
  binary_string = struct.pack(format, *values)
  return binary_string

def decode_user(binary_string):
  """
  Convert from  fixed-length binary vector to user_tuple
  :param binary_string: user as binary string
  :return: user tuple with ['id','name','email','phone',...]
  """
  values = struct.unpack(format, binary_string)
  values = [ value.decode('ascii').replace('\x00','') if not isinstance(value,int) else value for value in values]
  return values

#test:
first_row = df.iloc[0]
binary_row = encode_user(first_row)
print(f'first user: {first_row.values}')
print(binary_row)
print(f'encode: {len(binary_row)}')
#Remark that binary size is very large, due to padding to fixed length
#One solution (not implemented) is to work with varying length tuples,
#i.e. storing the length first and the characterd "3abc" instead of fixed-length padding like "00000000000abc"
first_row = decode_user(binary_row)
print(f'decode_user: {first_row}')

size of user: 302B
first user: [0 'Christopher Cabrera' 'jamestorres@lamb.info' '698-736-9201'
 'Jimenez Group' 'Stephanie Glens' 8 22740 'Niger' '1994-2-18' 0]
b'\x00\x00\x00\x00Christopher Cabrera\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00jamestorres@lamb.info\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00698-736-9201\x00\x00\x00\x00Jimenez Group\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Stephanie Glens\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00X\xd4Niger\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001994-2-18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
encode: 302
decode_user: [0, 'Christopher Cabrera', 'jamestorres@lamb.info', '698-736-9201', 'Jimenez Group', 'Stephanie Glens', 8, 22740, 'Niger', '1994-2-18', 0]

## Exercise 1: Save and load to binary file

**Exercise 1: Complete code to save and load from binary file**

Use *file* from python, see https://docs.python.org/3/tutorial/inputoutput.html

*file* API:

- *fh = open(filename, mode)*, e.g. mode can be "rb" (read binary), "rw" (write new binary file) or "r+b" (read and write existing binary file)
- *fh.read(N)* returns byte array with *N* bytes or False if nothing to read
- *fh.write(bytearray)* write (or appends) bytearray at current position
- *fh.seek(N)* go to file position starting at *N* bytes

In [299]:
def save_users_to_binary_file(filename, df):
    """
    Saves users to sorted fixed-length binary file
    :param filename: binary file to save
    :param df: pandas dataframe contains all users
    :return:
    """
#     start = time.time()
#     file = open(filename, "wb")
#     nr_of_rows = df.shape[0]
#     for i in range(0, nr_of_rows):
#         file.write(encode_user(df.iloc[i])) # df.iloc[i] is the i-th user tuple
#     file.close()
#     print(f'saved {nr_of_rows} records to {filename}. Time: {time.time() -start}s')

    start = time.time()

#     # Open the binary file in binary write mode
#     with open(filename, "wb") as file:
#         # Encode all user rows and write them to the binary file
#         for _, row in df.iterrows():
#             binary_row = encode_user(row)
#             file.write(binary_row)

    with open(filename, "wb") as file: # 0.18
        # Apply the encode_function to each row in the DataFrame and write to the file
        df.apply(lambda row: file.write(encode_user(row)), axis=1)

    print(f'saved {df.shape[0]} records to {filename}. Time: {time.time() - start}s')

def load_user_from_binary_file(filename,user_columns=user_columns):
    """
    Loads users from sorted fixed-length binary file
    :param filename: binary file to load
    :user_columns: name of columns
    :return: pandas dataframe with all user tuples
    """
    start = time.time()
    users = []

    file = open(filename, "rb")
    file.seek(0, 2) # seeking to the very end of the file
    file_size = file.tell() # current position = last byte of the file
    nr_of_rows = int(file_size / size_user)
    file.seek(0)

    for i in range(0, nr_of_rows):
        user_to_load = decode_user(file.read(size_user))
        if user_to_load[10] == 0:  # user isn't deleted
           users.append(user_to_load)
    file.close()
    print(f'loaded {nr_of_rows} records from {filename}. Time: {time.time() -start}s')
    df = pd.DataFrame(users,columns=user_columns)
    return df

In [300]:
#save
fname_bin = 'fake_users.bin'
save_users_to_binary_file(fname_bin, df)
file_size = os.stat(fname_bin).st_size
print(f"File size is {file_size}B")

saved 10000 records to fake_users.bin. Time: 0.12379097938537598s
File size is 3020000B

In [301]:
#load
df2 = load_user_from_binary_file(fname_bin)
display(df2)

loaded 10000 records from fake_users.bin. Time: 0.08966755867004395s

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,6490,Nigeria,1995-2-5,0
2,2,Danielle Sellers,katiecarroll@mcbride.com,267-932-7977,Macdonald Group,Spears Course,854,18101,Cayman Islands,1995-3-24,0
3,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,Papua New Guinea,2003-9-24,0
4,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,Iran,1970-6-23,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Angela Vance,ryan17@yahoo.com,993-213-6082,Mendoza Group,Caleb Lakes,212,38438,Martinique,1975-12-24,0
9996,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,3962,Samoa,1984-5-14,0
9997,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,Norway,1988-10-17,0
9998,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,Oman,1985-8-19,0
9999,9999,Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0

## Excercise 2: Random access

**Exercise 2: Complete code to save and load single a record using random access (i.e. file.seek)**

In [302]:
from logging import FileHandler
def read_user(user_id, fh):
    """
    Random access to read fixed-length user tuple in sorted file
    :param user_id: id of user data to read
    :param fh: file handle
    :return: decoded user tuple
    """
    offset = user_id * size_user
    fh.seek(offset)
    binary_row = fh.read(size_user)
    user_tuple = decode_user(binary_row)

    # user is deleted
    if user_tuple[10] == 1:
      return None

    return user_tuple

def write_user(user, fh):
    """
    Random acces to write/update fixed-length user tuple in sorted file
    :param user: user tuple/array where colums are ['id','name','email','phone',...]
    :param fh: file handle
    :return: -updated-user-tuple-in-file/ => void
    """
    offset = user[0] * size_user
    fh.seek(offset)
    binary_row = encode_user(user)
    fh.write(binary_row)

def delete_user(user_id, fh):
    """
    Delete user from database
    :param user_id: id of user data to delete
    :param fh: file handle
    :return: bool success
    """
    user_to_delete = read_user(user_id, fh)

    # already deleted
    if user_to_delete is None:
      return False

    else:
      user_to_delete[10] = 1
      write_user(user_to_delete, fh)
      return True

def insert_user(user, fh):
    """
    Insert user in database
    :param user: user to insert
    :param fh: file handle
    :return: bool success
    """
    fh.seek(0, 2) # seeking to the very end of the file
    file_size = fh.tell() # current position = last byte of the file
    new_id = int(file_size / size_user)
    user = [new_id] + user

    offset = file_size
    fh.seek(offset)
    binary_row = encode_user(user)
    fh.write(binary_row)

    return True

In [303]:
#Read 4 random users
fh = open(fname_bin,"rb")
start = time.time()
random_ids = [0, 100, 200, 9999]
random_users = []
for id in random_ids:
  user_i = read_user(id, fh)
  random_users.append(user_i)
print(f'Loading {len(random_ids)} random users. Elapsed: {time.time() -start}s')
fh.close()
df_sample = pd.DataFrame(random_users,columns=user_columns)
display(df_sample)

Loading 4 random users. Elapsed: 0.0006766319274902344s

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,100,Jeremy Brown,vbentley@gmail.com,479-429-9928,"Williams, Rose and Wilson",Lynn Crossing,589,61139,Niger,1983-11-27,0
2,200,Mrs. Danielle Russell,hernandezterri@robinson-reilly.net,796-485-7381,"Carter, Martinez and Benson",Marks Ville,228,13075,British Virgin Islands,1976-8-28,0
3,9999,Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0

In [304]:
#Update 4 random users
fh = open(fname_bin,"r+b") #open file for updating with "r+b", do not use "wb" since otherwise file will be blank!
start = time.time()
random_ids = [0, 100, 200, 9999]
for user in random_users:
  user[1] = 'X ' + user[1]
  write_user(user,fh)
print(f'Writing {len(random_ids)} random users. Elapsed: {time.time() -start}s')
fh.close()

Writing 4 random users. Elapsed: 0.002379894256591797s

In [305]:
# Check to see if users have been updated (X in front of name)
fh = open(fname_bin,"rb")
start = time.time()
random_ids = [0, 100, 200, 9999]
random_users = []
for id in random_ids:
  user_i = read_user(id, fh)
  random_users.append(user_i)
print(f'Loading {len(random_ids)} random users. Elapsed: {time.time() -start}s')
fh.close()
df_sample = pd.DataFrame(random_users,columns=user_columns)
display(df_sample)

Loading 4 random users. Elapsed: 0.0004949569702148438s

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,X Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,100,X Jeremy Brown,vbentley@gmail.com,479-429-9928,"Williams, Rose and Wilson",Lynn Crossing,589,61139,Niger,1983-11-27,0
2,200,X Mrs. Danielle Russell,hernandezterri@robinson-reilly.net,796-485-7381,"Carter, Martinez and Benson",Marks Ville,228,13075,British Virgin Islands,1976-8-28,0
3,9999,X Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0

In [306]:
# Delete user by id
fh = open(fname_bin,"r+b")
start = time.time()
ids_to_delete = [2] # use any
for _id in ids_to_delete:
  success = delete_user(_id, fh)
  if not success:
    print("User with id="+str(_id)+" is already deleted!")
print(f'deleting {len(ids_to_delete)} random users. Elapsed: {time.time() -start}s')
fh.close()
df_after_delete = load_user_from_binary_file(fname_bin)
display(df_after_delete)

deleting 1 random users. Elapsed: 0.0003287792205810547s
loaded 10000 records from fake_users.bin. Time: 0.20726442337036133s

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,X Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,6490,Nigeria,1995-2-5,0
2,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,Papua New Guinea,2003-9-24,0
3,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,Iran,1970-6-23,0
4,5,Eric Thompson,ringram@franklin.info,(776)423-4430,"Reese, Wade and Carr",Peterson Spur,410,76153,Italy,1980-4-10,0
...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,Angela Vance,ryan17@yahoo.com,993-213-6082,Mendoza Group,Caleb Lakes,212,38438,Martinique,1975-12-24,0
9995,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,3962,Samoa,1984-5-14,0
9996,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,Norway,1988-10-17,0
9997,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,Oman,1985-8-19,0
9998,9999,X Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0

In [307]:
# Insert user without id
fh = open(fname_bin,"r+b")
start = time.time()
fake = Faker()
new_user = [fake.name(), fake.ascii_email(), fake.basic_phone_number(), fake.company(), fake.street_name(), random.randint(1,1000), int(fake.zipcode()), fake.country(), f'{random.randint(1970,2005)}-{random.randint(1,12)}-{random.randint(1,28)}', 0]
insert_success = insert_user(new_user, fh)
fh.close()
print(f'inserting random user. Elapsed: {time.time() -start}s')

df_after_delete = load_user_from_binary_file(fname_bin)
display(df_after_delete)

inserting random user. Elapsed: 0.05982708930969238s
loaded 10001 records from fake_users.bin. Time: 0.1972658634185791s

,id,name,email,phone,company,street,street_number,zipcode,country,birthdate,deleted
0,0,X Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,Niger,1994-2-18,0
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,6490,Nigeria,1995-2-5,0
2,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,Papua New Guinea,2003-9-24,0
3,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,Iran,1970-6-23,0
4,5,Eric Thompson,ringram@franklin.info,(776)423-4430,"Reese, Wade and Carr",Peterson Spur,410,76153,Italy,1980-4-10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,3962,Samoa,1984-5-14,0
9996,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,Norway,1988-10-17,0
9997,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,Oman,1985-8-19,0
9998,9999,X Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,El Salvador,1999-9-3,0
9999,10000,Matthew Wright,erica94@gmail.com,(470)277-9693,Brady-Harris,Mary Knolls,439,27209,Lebanon,1973-7-27,0

# Compressed varying-length binary file

## Excercise 3: Modify dataframe and encode country using bitmap encoding
**Exercise 3: Encode country using bitmap encoding. You can assume the dictionary itself does not need to be stored**

*Pandas* API:
- *df[col]*: returns a single column with name *col* as series
- *df[col].values*: returns a single column as *numpy* array
- *list(df[col].values)*: returns a single column as *python* list
- *df[col].unique()*: returns all unique (or distinct) values
- *df[col].apply(f)*: applies (or runs) the function f to all column values
- *df[col2] = df[col].apply(f)*: applies (or runs) the function f to all column values and store the result in a new column

In [308]:
def encode_dictionary(df, col):
    """
    Creates column df[col + '_dct'] containing dictionary value
    :param df: pandas dataframe
    :param col: column to apply dictionary encoding
    :return mapping between value and code
    """
    unique_values = sorted(df[col].unique())
    value_to_code = {}
    for i in range(len(unique_values)):
        value_to_code[unique_values[i]] = i
    mapping = [(key,value) for key, value in value_to_code.items()]
    df["country_dct"] = df["country"].map(value_to_code)
    return mapping

In [309]:
"""
Before: col country is string. range: 4-51. unique: 243
After: country "id" encoded using dictionary and store as 16 bit integer
"""
value_to_code_countries = encode_dictionary(df,'country')
print(value_to_code_countries)

[('Afghanistan', 0), ('Albania', 1), ('Algeria', 2), ('American Samoa', 3), ('Andorra', 4), ('Angola', 5), ('Anguilla', 6), ('Antarctica (the territory South of 60 deg S)', 7), ('Antigua and Barbuda', 8), ('Argentina', 9), ('Armenia', 10), ('Aruba', 11), ('Australia', 12), ('Austria', 13), ('Azerbaijan', 14), ('Bahamas', 15), ('Bahrain', 16), ('Bangladesh', 17), ('Barbados', 18), ('Belarus', 19), ('Belgium', 20), ('Belize', 21), ('Benin', 22), ('Bermuda', 23), ('Bhutan', 24), ('Bolivia', 25), ('Bosnia and Herzegovina', 26), ('Botswana', 27), ('Bouvet Island (Bouvetoya)', 28), ('Brazil', 29), ('British Indian Ocean Territory (Chagos Archipelago)', 30), ('British Virgin Islands', 31), ('Brunei Darussalam', 32), ('Bulgaria', 33), ('Burkina Faso', 34), ('Burundi', 35), ('Cambodia', 36), ('Cameroon', 37), ('Canada', 38), ('Cape Verde', 39), ('Cayman Islands', 40), ('Central African Republic', 41), ('Chad', 42), ('Chile', 43), ('China', 44), ('Christmas Island', 45), ('Cocos (Keeling) Islands', 46), ('Colombia', 47), ('Comoros', 48), ('Congo', 49), ('Cook Islands', 50), ('Costa Rica', 51), ("Cote d'Ivoire", 52), ('Croatia', 53), ('Cuba', 54), ('Cyprus', 55), ('Czech Republic', 56), ('Denmark', 57), ('Djibouti', 58), ('Dominica', 59), ('Dominican Republic', 60), ('Ecuador', 61), ('Egypt', 62), ('El Salvador', 63), ('Equatorial Guinea', 64), ('Eritrea', 65), ('Estonia', 66), ('Ethiopia', 67), ('Falkland Islands (Malvinas)', 68), ('Faroe Islands', 69), ('Fiji', 70), ('Finland', 71), ('France', 72), ('French Guiana', 73), ('French Polynesia', 74), ('French Southern Territories', 75), ('Gabon', 76), ('Gambia', 77), ('Georgia', 78), ('Germany', 79), ('Ghana', 80), ('Gibraltar', 81), ('Greece', 82), ('Greenland', 83), ('Grenada', 84), ('Guadeloupe', 85), ('Guam', 86), ('Guatemala', 87), ('Guernsey', 88), ('Guinea', 89), ('Guinea-Bissau', 90), ('Guyana', 91), ('Haiti', 92), ('Heard Island and McDonald Islands', 93), ('Holy See (Vatican City State)', 94), ('Honduras', 95), ('Hong Kong', 96), ('Hungary', 97), ('Iceland', 98), ('India', 99), ('Indonesia', 100), ('Iran', 101), ('Iraq', 102), ('Ireland', 103), ('Isle of Man', 104), ('Israel', 105), ('Italy', 106), ('Jamaica', 107), ('Japan', 108), ('Jersey', 109), ('Jordan', 110), ('Kazakhstan', 111), ('Kenya', 112), ('Kiribati', 113), ('Korea', 114), ('Kuwait', 115), ('Kyrgyz Republic', 116), ("Lao People's Democratic Republic", 117), ('Latvia', 118), ('Lebanon', 119), ('Lesotho', 120), ('Liberia', 121), ('Libyan Arab Jamahiriya', 122), ('Liechtenstein', 123), ('Lithuania', 124), ('Luxembourg', 125), ('Macao', 126), ('Madagascar', 127), ('Malawi', 128), ('Malaysia', 129), ('Maldives', 130), ('Mali', 131), ('Malta', 132), ('Marshall Islands', 133), ('Martinique', 134), ('Mauritania', 135), ('Mauritius', 136), ('Mayotte', 137), ('Mexico', 138), ('Micronesia', 139), ('Moldova', 140), ('Monaco', 141), ('Mongolia', 142), ('Montenegro', 143), ('Montserrat', 144), ('Morocco', 145), ('Mozambique', 146), ('Myanmar', 147), ('Namibia', 148), ('Nauru', 149), ('Nepal', 150), ('Netherlands', 151), ('Netherlands Antilles', 152), ('New Caledonia', 153), ('New Zealand', 154), ('Nicaragua', 155), ('Niger', 156), ('Nigeria', 157), ('Niue', 158), ('Norfolk Island', 159), ('North Macedonia', 160), ('Northern Mariana Islands', 161), ('Norway', 162), ('Oman', 163), ('Pakistan', 164), ('Palau', 165), ('Palestinian Territory', 166), ('Panama', 167), ('Papua New Guinea', 168), ('Paraguay', 169), ('Peru', 170), ('Philippines', 171), ('Pitcairn Islands', 172), ('Poland', 173), ('Portugal', 174), ('Puerto Rico', 175), ('Qatar', 176), ('Reunion', 177), ('Romania', 178), ('Russian Federation', 179), ('Rwanda', 180), ('Saint Barthelemy', 181), ('Saint Helena', 182), ('Saint Kitts and Nevis', 183), ('Saint Lucia', 184), ('Saint Martin', 185), ('Saint Pierre and Miquelon', 186), ('Saint Vincent and the Grenadines', 187), ('Samoa', 188), ('San Marino', 189), ('Sao Tome and Principe', 190), ('Saudi Arabia', 191), ('Senegal', 192), ('Serbia', 193), ('Seychelles', 194), ('Sierra Leone', 195), ('Singapore', 196), ('Slovakia (Slovak Republic)', 197), ('Slovenia', 198), ('Solomon Islands', 199), ('Somalia', 200), ('South Africa', 201), ('South Georgia and the South Sandwich Islands', 202), ('Spain', 203), ('Sri Lanka', 204), ('Sudan', 205), ('Suriname', 206), ('Svalbard & Jan Mayen Islands', 207), ('Swaziland', 208), ('Sweden', 209), ('Switzerland', 210), ('Syrian Arab Republic', 211), ('Taiwan', 212), ('Tajikistan', 213), ('Tanzania', 214), ('Thailand', 215), ('Timor-Leste', 216), ('Togo', 217), ('Tokelau', 218), ('Tonga', 219), ('Trinidad and Tobago', 220), ('Tunisia', 221), ('Turkey', 222), ('Turkmenistan', 223), ('Turks and Caicos Islands', 224), ('Tuvalu', 225), ('Uganda', 226), ('Ukraine', 227), ('United Arab Emirates', 228), ('United Kingdom', 229), ('United States Minor Outlying Islands', 230), ('United States Virgin Islands', 231), ('United States of America', 232), ('Uruguay', 233), ('Uzbekistan', 234), ('Vanuatu', 235), ('Venezuela', 236), ('Vietnam', 237), ('Wallis and Futuna', 238), ('Western Sahara', 239), ('Yemen', 240), ('Zambia', 241), ('Zimbabwe', 242)]

## Timestamp encoding of birthdate
Birthdate encoded as string, i.e. "1986-11-20" takes 10 bytes. Encodes
as timestamp, i.e. number of seconds since January 1st, 1970, takes 4 bytes.

In [310]:
import datetime
"""
col birthdate is string. range: 8-10. unique: 7971
  -> Convert to timestamp  with 32bits
"""
df['birthdate_ts'] = df['birthdate'].apply(lambda s:  pd.to_datetime(s,format='%Y-%m-%d'))
df['birthdate_ts'] = df['birthdate_ts'].astype(int) / 10**9

In [311]:
df = df[['id', 'name', 'email', 'phone', 'company', 'street', 'street_number', 'zipcode', 'country_dct', 'birthdate_ts']]
display(df)
new_user_columns = list(df.columns.values)
print(new_user_columns)

,id,name,email,phone,company,street,street_number,zipcode,country_dct,birthdate_ts
0,0,Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,156,7.615296e+08
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,6490,157,7.919424e+08
2,2,Danielle Sellers,katiecarroll@mcbride.com,267-932-7977,Macdonald Group,Spears Course,854,18101,40,7.960032e+08
3,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,168,1.064362e+09
4,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,101,1.494720e+07
...,...,...,...,...,...,...,...,...,...,...
9995,9995,Angela Vance,ryan17@yahoo.com,993-213-6082,Mendoza Group,Caleb Lakes,212,38438,134,1.886112e+08
9996,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,3962,188,4.533408e+08
9997,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,162,5.930496e+08
9998,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,163,4.932576e+08
9999,9999,Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,63,9.363168e+08

['id', 'name', 'email', 'phone', 'company', 'street', 'street_number', 'zipcode', 'country_dct', 'birthdate_ts']

# Varying-length binary file

## Encode variable-length tuples

In [312]:
#some constants for efficiency
IDX_ID = new_user_columns.index('id')
IDX_SN = new_user_columns.index('street_number')
IDX_ZIP = new_user_columns.index('zipcode')
IDX_BD = new_user_columns.index('birthdate_ts')
IDX_COUNTRY = new_user_columns.index('country_dct')
IDX_NAME = new_user_columns.index('name')
IDX_EMAIL = new_user_columns.index('email')
IDX_PHONE = new_user_columns.index('phone')
IDX_COMPANY = new_user_columns.index('company')
IDX_STREET = new_user_columns.index('street')

def encode_var_string(s):
  return [len(s)] + list(s.encode('ascii'))

def encode_user_var_length(user):
  '''
  Assuming user has columns
  ['id', 'name', 'email', 'phone', 'company', 'street', 'street_number', 'zipcode', 'country_dct', 'birthdate_ts']

  encode user object:
  id, street_number, zipcode, birthdate_ts, country_dct
    -> to integer between 1 and 4 bytes depending on range values
  name, email, phone, company, street
    -> to variable-length string, e.g. "helloworld" -> (8,"helloworld") instead of using padding, e.g."0000000helloworld"
  '''
  int_list = []
  int_list.extend(int(user[IDX_ID]).to_bytes(4,'little'))
  int_list.extend(int(user[IDX_SN]).to_bytes(2,'little')) #max street number < 65536 (or 2^16)
  int_list.extend(int(user[IDX_ZIP]).to_bytes(4,'little'))
  int_list.extend(int(user[IDX_BD]).to_bytes(4,'little'))
  int_list.extend(int(user[IDX_COUNTRY]).to_bytes(1,'little')) #max country < 256 (or 2^8)
  int_list.extend(encode_var_string(user[IDX_NAME]))
  int_list.extend(encode_var_string(user[IDX_EMAIL]))
  int_list.extend(encode_var_string(user[IDX_PHONE]))
  int_list.extend(encode_var_string(user[IDX_COMPANY]))
  int_list.extend(encode_var_string(user[IDX_STREET]))
  return bytearray(int_list)

## Excercise 4: Write code to decode byte_array

**Exercise 4: Complete the following code to decode a single user tuple encoded as bytes using encode_user_var_length**
API:
- *byte_array[start:end]* : get sub-array of bytes
- *int.from_bytes(byte_array_slice, "little")*: get python integer from byte array. Note that small integer can be 1 byte, and large integer can be 4 bytes or more.
- *str(byte_array_slice, encoding='ascii')*: get python string encoded as ascii

In [313]:
def decode_user_var_length(byte_array):
    '''
    decode variable-length tuple representing user (see encode_user_var_length)
    '''
    id = int.from_bytes(byte_array[0:4], byteorder='little')
    street_number = int.from_bytes(byte_array[4:6], byteorder='little')
    zipcode = int.from_bytes(byte_array[6:10], byteorder='little')
    bd = int.from_bytes(byte_array[10:14], byteorder='little')
    country_dct = int.from_bytes(byte_array[14:15], byteorder='little')

    name_len = int.from_bytes(byte_array[15:16], "little")
    name = byte_array[16:16+name_len].decode('ascii')
    email_len = int.from_bytes(byte_array[16+name_len:16+name_len+1], "little")
    email = byte_array[16+name_len+1:16+name_len+1+email_len].decode('ascii')
    phone_len = int.from_bytes(byte_array[16+name_len+1+email_len:16+name_len+1+email_len+1], "little")
    phone = byte_array[16+name_len+1+email_len+1:16+name_len+1+email_len+1+phone_len].decode('ascii')
    company_len = int.from_bytes(byte_array[16+name_len+1+email_len+1+phone_len:16+name_len+1+email_len+1+phone_len+1], "little")
    company = byte_array[16+name_len+1+email_len+1+phone_len+1:16+name_len+1+email_len+1+phone_len+1+company_len].decode('ascii')
    street_len = int.from_bytes(byte_array[16+name_len+1+email_len+1+phone_len+1+company_len:16+name_len+1+email_len+1+phone_len+1+company_len+1], "little")
    street = byte_array[16+name_len+1+email_len+1+phone_len+1+company_len+1:16+name_len+1+email_len+1+phone_len+1+company_len+1+street_len].decode('ascii')
    l = [id, name, email, phone, company, street, street_number, zipcode, country_dct, bd]

#     loop variant, does the same, but probably a bit slower
#     i = 0
#     next_start = 16
#     len_next = int.from_bytes(byte_array[15:16], "little")
#     user_values = []
#     while i < 5:
#         start = next_start
#         user_values.append(byte_array[start:start+len_next].decode("ascii"))
#         next_start = start+len_next+1
#         if i != 4:
#             len_next = int.from_bytes(byte_array[start+len_next:start+len_next+1], "little")
#         i += 1

#     l = [id]
#     l.extend(user_values)
#     l.extend([street_number, zipcode, country_dct, bd])

    return l

In [314]:
#test
first_user = df.iloc[0]
print(first_user.values)
byte_array = encode_user_var_length(first_user)
print(f'byte array len: {len(byte_array)}: {byte_array}') #107 bytes instead of 298 bytes!
start = time.time()
user = decode_user_var_length(byte_array)
print(f'Decoding. Elapsed: {time.time() -start}s')
print(f'decoded: {user}')

[0 'Christopher Cabrera' 'jamestorres@lamb.info' '698-736-9201'
 'Jimenez Group' 'Stephanie Glens' 8 22740 156 761529600.0]
byte array len: 100: bytearray(b'\x00\x00\x00\x00\x08\x00\xd4X\x00\x00\x00\x05d-\x9c\x13Christopher Cabrera\x15jamestorres@lamb.info\x0c698-736-9201\rJimenez Group\x0fStephanie Glens')
Decoding. Elapsed: 0.00017309188842773438s
decoded: [0, 'Christopher Cabrera', 'jamestorres@lamb.info', '698-736-9201', 'Jimenez Group', 'Stephanie Glens', 8, 22740, 156, 761529600]

## Save and load to file varying-length to binary file
Use slotted pages. Start of file contains array of N integer (32 bits) with location of tuples. Then we store varying-lengh binary encoding of tuples sequentially.

## Excercise 5: Save varying-length user tuples
Write code to save header containing offsets to tuples and tuples in binary file. Also write code to read binary file.

The file layout could be: $[N, \mathit{offset}_1, \mathit{offset}_2, \ldots, \mathit{offset}_N, \mathit{offset}_{N+1}, t_1, t_2, \ldots, t_N]$

In [315]:
def save_users_to_binary_var_length(filename, df):
    """
    saves users to sorted variable-length binary file
    file layout: [N offset_t1 offset_t2... offset_tN offset_tN+1 t1 t2 ... tN]

    :param filename: binary file to save
    :param df: pandas dataframe contains all users
    :return:
    """
    start = time.time()
    number_of_slots = df.shape[0]
    offsets = [0]
    binary_data = b''
    for i in range(number_of_slots):
        user_data = encode_user_var_length(df.iloc[i])
        binary_data += user_data
        offsets.append(len(binary_data))

    with open(filename, "wb") as file:
        file.write(number_of_slots.to_bytes(4, 'little')) # N at beginning of file
        for offset in offsets: # nr of offsets = nr of rows
            file.write(offset.to_bytes(4, 'little'))
        file.write(binary_data)

    file.close()
    print(f'saved {number_of_slots} records to {filename}. Time: {time.time() -start}s')

#     testing (fyi everytime you 'Run All' the users can change because of faker)
#     file = open(filename, "rb")
#     file.seek(0)
#     a = file.read(100)
#     b = int.from_bytes(a[12:16], byteorder='little')
#     print(b)
#     file.close()

def load_users_from_binary_var_length(filename):
    """
    load users from sorted variable-length binary file
    file layout: [N offset_t1 offset_t2... offset_tN offset_tN+1 t1 t2 ... tN]

    :param filename: binary file to save
    :return: pandas dataframe contains all users
    """
    start = time.time()
    # load header and user data
    with open(filename, "rb") as file:
        number_of_slots = int.from_bytes(file.read(4), 'little') # N at beginning
        offsets = [int.from_bytes(file.read(4), 'little') for i in range(number_of_slots+1)] # nr of offsets = nr of rows
        binary_data = file.read() # rest of the file
    # extract users
    users = []
    for i in range(number_of_slots):
        users.append(decode_user_var_length(binary_data[offsets[i]:offsets[i+1]])) # ~= append( decode( encoded_user[i] ) )

    print(f'Loaded {number_of_slots} records from {filename}. Time: {time.time() - start}s')
    df = pd.DataFrame(users, columns=new_user_columns)
    return df

In [316]:
#save
fname_bin = 'fake_users.bin2'
save_users_to_binary_var_length(fname_bin, df)
file_size = os.stat(fname_bin).st_size
print(f"File size is {file_size}B") #was 2980000B, know 999927B (about 33% of fixed-length)

saved 10000 records to fake_users.bin2. Time: 3.8438727855682373s
File size is 1001810B

In [317]:
#load
df2 = load_users_from_binary_var_length(fname_bin)
display(df2)

Loaded 10000 records from fake_users.bin2. Time: 0.15322303771972656s

,id,name,email,phone,company,street,street_number,zipcode,country_dct,birthdate_ts
0,0,Christopher Cabrera,jamestorres@lamb.info,698-736-9201,Jimenez Group,Stephanie Glens,8,22740,156,761529600
1,1,Alan Johnson,danielle36@yahoo.com,316-491-8242,"Reyes, Murphy and Sampson",Evans Key,922,6490,157,791942400
2,2,Danielle Sellers,katiecarroll@mcbride.com,267-932-7977,Macdonald Group,Spears Course,854,18101,40,796003200
3,3,Joseph Mathews,robert97@howe.biz,(519)607-1190,Byrd and Sons,Stephen Causeway,551,63150,168,1064361600
4,4,Valerie Vargas,huntermatthew@hotmail.com,3069871174,Edwards PLC,Robin Loaf,235,15539,101,14947200
...,...,...,...,...,...,...,...,...,...,...
9995,9995,Angela Vance,ryan17@yahoo.com,993-213-6082,Mendoza Group,Caleb Lakes,212,38438,134,188611200
9996,9996,Ricky Thomas,gordonmichael@gmail.com,(932)634-1384,"Rios, Brooks and Ford",Rebecca Station,832,3962,188,453340800
9997,9997,Annette Boyle,nmorrison@miller.info,573-987-8380,Smith-Mccoy,Bruce Cliffs,563,49556,162,593049600
9998,9998,April Thomas,morrowchristopher@gray-williams.org,(922)585-2365,"Kaiser, Banks and Stephens",Ryan Mall,465,31100,163,493257600
9999,9999,Sandra Calhoun,hnichols@gmail.com,982-757-4989,"Holmes, Mejia and Dudley",Travis Bypass,743,94040,63,936316800